dashboardWebApplication:
  enabled: true
  name: dashboard-web-application
  nodeSelector: 
    role: usernp1
  image: 
    repository: acr7c02.azurecr.io/demo8020-dashboard-web-application
    pullPolicy: IfNotPresent  
    tag: "0.0.6"
  applicationPrefix: "/radiology"
  applicationName: "Radiology"
  signinUri: "https://$host/auth/radiology/start?rd=$escaped_request_uri"
  authUri: "https://$host/auth/radiology/auth"
  
reportWriter:
  enabled: true
  name: report-writer
  schedule: "0 0 * * *"
  nodeSelector: 
    role: usernp2
  image: 
    repository: acr7c02.azurecr.io/demo8020-report-writer
    pullPolicy: IfNotPresent  
    tag: "0.0.6"
  keyVaultUrl: "https://vault7c02.vault.azure.net"
  secretName: "mongo-connection"
  databaseName: "PatientData"
  collectionName: "Default"

reportWriterServiceAccount:
  enabled: true
  name: radiologysvc
  clientId: "1125150f-9f14-45aa-be81-dfbc86c91a24"

persistentVolumeClaim:
  enabled: true
  name: store7c02a-container02-claim

persistentVolume:
  enabled: true
  name: store7c02a-container02
  azureResourceGroup: 2023-12-04-RG-01
  azureStorageAccount: store7c02a
  azureBlobContainer: container02
