dashboardWebApplication:
  enabled: true
  name: dashboard-web-application
  nodeSelector: 
    role: usernp1
  image: 
    repository: acr7c02.azurecr.io/demo8020-dashboard-web-application
    pullPolicy: IfNotPresent  
    tag: "0.0.3"
  applicationPrefix: "/oncology"
  applicationName: "Oncology"
  signinUri: "https://$host/auth/oncology/start?rd=$escaped_request_uri"
  authUri: "https://$host/auth/oncology/auth"
  
reportWriter:
  enabled: true
  name: report-writer
  schedule: "0 0 * * *"
  nodeSelector: 
    role: usernp2
  image: 
    repository: acr7c02.azurecr.io/demo8020-report-writer
    pullPolicy: IfNotPresent  
    tag: "0.0.3"
  keyVaultUrl: "https://vault7c02.vault.azure.net"
  secretName: "mongo-connection"
  databaseName: "PatientData"
  collectionName: "Default"

reportWriterServiceAccount:
  enabled: true
  name: oncologysvc
  clientId: "94e6b2ea-b0a3-478e-b02f-491fae30b7a1"

persistentVolumeClaim:
  enabled: true
  name: store7c02a-container04-claim

persistentVolume:
  enabled: true
  name: store7c02a-container04
  azureResourceGroup: 2023-12-04-RG-01
  azureStorageAccount: store7c02a
  azureBlobContainer: container04